import { PrismaClient } from '@prisma/client';

//cargar una lista de aeropuertos en la bd
export async function seedAirports(prisma: PrismaClient){

    //Lista de de hubs, aeropuertos secundarios y aeropuertos relevantes para guardar en la bd
    const airports = [
    // --- EUROPA (Hubs y Secundarios) ---
    { iata: "MAD", name: "Adolfo Suárez Madrid-Barajas", city: "Madrid", country: "Spain" },
    { iata: "BCN", name: "Josep Tarradellas Barcelona-El Prat", city: "Barcelona", country: "Spain" },
    { iata: "PMI", name: "Palma de Mallorca", city: "Palma", country: "Spain" },
    { iata: "AGP", name: "Málaga-Costa del Sol", city: "Málaga", country: "Spain" },
    { iata: "ALC", name: "Alicante-Elche Miguel Hernández", city: "Alicante", country: "Spain" },
    { iata: "VLC", name: "Valencia", city: "Valencia", country: "Spain" },
    { iata: "LHR", name: "London Heathrow", city: "London", country: "United Kingdom" },
    { iata: "LGW", name: "London Gatwick", city: "London", country: "United Kingdom" },
    { iata: "STN", name: "London Stansted", city: "London", country: "United Kingdom" },
    { iata: "MAN", name: "Manchester", city: "Manchester", country: "United Kingdom" },
    { iata: "CDG", name: "Paris Charles de Gaulle", city: "Paris", country: "France" },
    { iata: "ORY", name: "Paris Orly", city: "Paris", country: "France" },
    { iata: "NCE", name: "Nice Côte d'Azur", city: "Nice", country: "France" },
    { iata: "FRA", name: "Frankfurt am Main", city: "Frankfurt", country: "Germany" },
    { iata: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
    { iata: "BER", name: "Berlin Brandenburg", city: "Berlin", country: "Germany" },
    { iata: "AMS", name: "Amsterdam Schiphol", city: "Amsterdam", country: "Netherlands" },
    { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
    { iata: "SAW", name: "Sabiha Gökçen International", city: "Istanbul", country: "Turkey" },
    { iata: "FCO", name: "Leonardo da Vinci–Fiumicino", city: "Rome", country: "Italy" },
    { iata: "MXP", name: "Milan Malpensa", city: "Milan", country: "Italy" },
    { iata: "ZRH", name: "Zurich", city: "Zurich", country: "Switzerland" },
    { iata: "VIE", name: "Vienna International", city: "Vienna", country: "Austria" },
    { iata: "CPH", name: "Copenhagen", city: "Copenhagen", country: "Denmark" },
    { iata: "ARN", name: "Stockholm Arlanda", city: "Stockholm", country: "Sweden" },
    { iata: "OSL", name: "Oslo Gardermoen", city: "Oslo", country: "Norway" },
    { iata: "HEL", name: "Helsinki-Vantaa", city: "Helsinki", country: "Finland" },
    { iata: "DUB", name: "Dublin", city: "Dublin", country: "Ireland" },
    { iata: "LIS", name: "Humberto Delgado", city: "Lisbon", country: "Portugal" },
    { iata: "OPO", name: "Francisco Sá Carneiro", city: "Porto", country: "Portugal" },
    { iata: "ATH", name: "Athens International", city: "Athens", country: "Greece" },
    { iata: "WAW", name: "Warsaw Chopin", city: "Warsaw", country: "Poland" },
    { iata: "PRG", name: "Václav Havel Prague", city: "Prague", country: "Czech Republic" },
    { iata: "BRU", name: "Brussels", city: "Brussels", country: "Belgium" },

    // --- NORTEAMÉRICA (USA, Canada, Mexico) ---
    { iata: "ATL", name: "Hartsfield–Jackson Atlanta International", city: "Atlanta", country: "United States" },
    { iata: "DFW", name: "Dallas/Fort Worth International", city: "Dallas", country: "United States" },
    { iata: "DEN", name: "Denver International", city: "Denver", country: "United States" },
    { iata: "ORD", name: "O'Hare International", city: "Chicago", country: "United States" },
    { iata: "LAX", name: "Los Angeles International", city: "Los Angeles", country: "United States" },
    { iata: "JFK", name: "John F. Kennedy International", city: "New York", country: "United States" },
    { iata: "LGA", name: "LaGuardia", city: "New York", country: "United States" },
    { iata: "EWR", name: "Newark Liberty International", city: "Newark", country: "United States" },
    { iata: "MIA", name: "Miami International", city: "Miami", country: "United States" },
    { iata: "SFO", name: "San Francisco International", city: "San Francisco", country: "United States" },
    { iata: "SEA", name: "Seattle-Tacoma International", city: "Seattle", country: "United States" },
    { iata: "LAS", name: "Harry Reid International", city: "Las Vegas", country: "United States" },
    { iata: "MCO", name: "Orlando International", city: "Orlando", country: "United States" },
    { iata: "PHX", name: "Phoenix Sky Harbor", city: "Phoenix", country: "United States" },
    { iata: "IAH", name: "George Bush Intercontinental", city: "Houston", country: "United States" },
    { iata: "CLT", name: "Charlotte Douglas", city: "Charlotte", country: "United States" },
    { iata: "BOS", name: "Boston Logan", city: "Boston", country: "United States" },
    { iata: "MSP", name: "Minneapolis-Saint Paul", city: "Minneapolis", country: "United States" },
    { iata: "DTW", name: "Detroit Metropolitan", city: "Detroit", country: "United States" },
    { iata: "PHL", name: "Philadelphia International", city: "Philadelphia", country: "United States" },
    { iata: "YYZ", name: "Toronto Pearson", city: "Toronto", country: "Canada" },
    { iata: "YVR", name: "Vancouver International", city: "Vancouver", country: "Canada" },
    { iata: "YUL", name: "Montréal-Trudeau", city: "Montreal", country: "Canada" },
    { iata: "YYC", name: "Calgary International", city: "Calgary", country: "Canada" },
    { iata: "MEX", name: "Benito Juárez International", city: "Mexico City", country: "Mexico" },
    { iata: "CUN", name: "Cancún International", city: "Cancun", country: "Mexico" },
    { iata: "GDL", name: "Guadalajara International", city: "Guadalajara", country: "Mexico" },
    { iata: "MTY", name: "Monterrey International", city: "Monterrey", country: "Mexico" },

    // --- ASIA & PACÍFICO ---
    { iata: "HND", name: "Tokyo Haneda", city: "Tokyo", country: "Japan" },
    { iata: "NRT", name: "Narita International", city: "Tokyo", country: "Japan" },
    { iata: "KIX", name: "Kansai International", city: "Osaka", country: "Japan" },
    { iata: "ICN", name: "Incheon International", city: "Seoul", country: "South Korea" },
    { iata: "SIN", name: "Singapore Changi", city: "Singapore", country: "Singapore" },
    { iata: "HKG", name: "Hong Kong International", city: "Hong Kong", country: "China" },
    { iata: "PVG", name: "Shanghai Pudong", city: "Shanghai", country: "China" },
    { iata: "SHA", name: "Shanghai Hongqiao", city: "Shanghai", country: "China" },
    { iata: "PEK", name: "Beijing Capital", city: "Beijing", country: "China" },
    { iata: "PKX", name: "Beijing Daxing", city: "Beijing", country: "China" },
    { iata: "CAN", name: "Guangzhou Baiyun", city: "Guangzhou", country: "China" },
    { iata: "SZX", name: "Shenzhen Bao'an", city: "Shenzhen", country: "China" },
    { iata: "TPE", name: "Taiwan Taoyuan", city: "Taipei", country: "Taiwan" },
    { iata: "BKK", name: "Suvarnabhumi", city: "Bangkok", country: "Thailand" },
    { iata: "DMK", name: "Don Mueang International", city: "Bangkok", country: "Thailand" },
    { iata: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "Malaysia" },
    { iata: "MNL", name: "Ninoy Aquino International", city: "Manila", country: "Philippines" },
    { iata: "SGN", name: "Tan Son Nhat International", city: "Ho Chi Minh City", country: "Vietnam" },
    { iata: "DEL", name: "Indira Gandhi International", city: "Delhi", country: "India" },
    { iata: "BOM", name: "Chhatrapati Shivaji Maharaj", city: "Mumbai", country: "India" },
    { iata: "BLR", name: "Kempegowda International", city: "Bangalore", country: "India" },
    { iata: "SYD", name: "Sydney Kingsford Smith", city: "Sydney", country: "Australia" },
    { iata: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
    { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
    { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },

    // --- ORIENTE MEDIO & ÁFRICA ---
    { iata: "DXB", name: "Dubai International", city: "Dubai", country: "United Arab Emirates" },
    { iata: "DWC", name: "Al Maktoum International", city: "Dubai", country: "United Arab Emirates" },
    { iata: "DOH", name: "Hamad International", city: "Doha", country: "Qatar" },
    { iata: "AUH", name: "Zayed International", city: "Abu Dhabi", country: "United Arab Emirates" },
    { iata: "RUH", name: "King Khalid International", city: "Riyadh", country: "Saudi Arabia" },
    { iata: "JED", name: "King Abdulaziz International", city: "Jeddah", country: "Saudi Arabia" },
    { iata: "CAI", name: "Cairo International", city: "Cairo", country: "Egypt" },
    { iata: "JNB", name: "O. R. Tambo International", city: "Johannesburg", country: "South Africa" },
    { iata: "CPT", name: "Cape Town International", city: "Cape Town", country: "South Africa" },
    { iata: "ADD", name: "Addis Ababa Bole", city: "Addis Ababa", country: "Ethiopia" },
    { iata: "CMN", name: "Mohammed V International", city: "Casablanca", country: "Morocco" },
    { iata: "NBO", name: "Jomo Kenyatta International", city: "Nairobi", country: "Kenya" },

    // --- LATINOAMÉRICA ---
    { iata: "GRU", name: "São Paulo/Guarulhos International", city: "São Paulo", country: "Brazil" },
    { iata: "CGH", name: "São Paulo/Congonhas", city: "São Paulo", country: "Brazil" },
    { iata: "GIG", name: "Rio de Janeiro/Galeão", city: "Rio de Janeiro", country: "Brazil" },
    { iata: "BOG", name: "El Dorado International", city: "Bogotá", country: "Colombia" },
    { iata: "LIM", name: "Jorge Chávez International", city: "Lima", country: "Peru" },
    { iata: "SCL", name: "Arturo Merino Benítez", city: "Santiago", country: "Chile" },
    { iata: "EZE", name: "Ministro Pistarini International", city: "Buenos Aires", country: "Argentina" },
    { iata: "AEP", name: "Aeroparque Jorge Newbery", city: "Buenos Aires", country: "Argentina" },
    { iata: "PTY", name: "Tocumen International", city: "Panama City", country: "Panama" },
    { iata: "SJO", name: "Juan Santamaría International", city: "San José", country: "Costa Rica" },
    { iata: "UIO", name: "Mariscal Sucre International", city: "Quito", country: "Ecuador" },
    { iata: "MDE", name: "José María Córdova", city: "Medellín", country: "Colombia" },

    // --- ADICIONALES (Secundarios y Regionales Relevantes) ---
    { iata: "VCP", name: "Viracopos International", city: "Campinas", country: "Brazil" },
    { iata: "BSB", name: "Brasília International", city: "Brasília", country: "Brazil" },
    { iata: "PUJ", name: "Punta Cana International", city: "Punta Cana", country: "Dominican Republic" },
    { iata: "SDQ", name: "Las Américas International", city: "Santo Domingo", country: "Dominican Republic" },
    { iata: "GUA", name: "La Aurora International", city: "Guatemala City", country: "Guatemala" },
    { iata: "SAL", name: "El Salvador International", city: "San Salvador", country: "El Salvador" },
    { iata: "GIG", name: "Galeão International", city: "Rio de Janeiro", country: "Brazil" },
    { iata: "VVI", name: "Viru Viru International", city: "Santa Cruz", country: "Bolivia" },
    { iata: "ASU", name: "Silvio Pettirossi", city: "Asunción", country: "Paraguay" },
    { iata: "MVD", name: "Carrasco International", city: "Montevideo", country: "Uruguay" },
    { iata: "LYS", name: "Lyon–Saint-Exupéry", city: "Lyon", country: "France" },
    { iata: "MRS", name: "Marseille Provence", city: "Marseille", country: "France" },
    { iata: "TLS", name: "Toulouse–Blagnac", city: "Toulouse", country: "France" },
    { iata: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany" },
    { iata: "DUS", name: "Düsseldorf", city: "Düsseldorf", country: "Germany" },
    { iata: "STR", name: "Stuttgart", city: "Stuttgart", country: "Germany" },
    { iata: "VCE", name: "Venice Marco Polo", city: "Venice", country: "Italy" },
    { iata: "NAP", name: "Naples International", city: "Naples", country: "Italy" },
    { iata: "CTA", name: "Catania–Fontanarossa", city: "Catania", country: "Italy" },
    { iata: "EDI", name: "Edinburgh", city: "Edinburgh", country: "United Kingdom" },
    { iata: "BHX", name: "Birmingham", city: "Birmingham", country: "United Kingdom" },
    { iata: "GLA", name: "Glasgow", city: "Glasgow", country: "United Kingdom" },
    { iata: "BRS", name: "Bristol", city: "Bristol", country: "United Kingdom" },
    { iata: "SNN", name: "Shannon", city: "Shannon", country: "Ireland" },
    { iata: "GVA", name: "Geneva", city: "Geneva", country: "Switzerland" },
    { iata: "BSL", name: "EuroAirport Basel Mulhouse Freiburg", city: "Basel", country: "Switzerland" },
    { iata: "SVG", name: "Stavanger", city: "Stavanger", country: "Norway" },
    { iata: "BGO", name: "Bergen", city: "Bergen", country: "Norway" },
    { iata: "GOT", name: "Göteborg Landvetter", city: "Gothenburg", country: "Sweden" },
    { iata: "BLL", name: "Billund", city: "Billund", country: "Denmark" },
    { iata: "KRK", name: "Kraków John Paul II", city: "Kraków", country: "Poland" },
    { iata: "BUD", name: "Budapest Ferenc Liszt", city: "Budapest", country: "Hungary" },
    { iata: "OTP", name: "Henri Coandă", city: "Bucharest", country: "Romania" },
    { iata: "BEG", name: "Belgrade Nikola Tesla", city: "Belgrade", country: "Serbia" },
    { iata: "VNO", name: "Vilnius", city: "Vilnius", country: "Lithuania" },
    { iata: "TLL", name: "Tallinn", city: "Tallinn", country: "Estonia" },
    { iata: "RIX", name: "Riga", city: "Riga", country: "Latvia" },
    { iata: "AYT", name: "Antalya", city: "Antalya", country: "Turkey" },
    { iata: "ESB", name: "Esenboğa", city: "Ankara", country: "Turkey" },
    { iata: "ADB", name: "Adnan Menderes", city: "Izmir", country: "Turkey" },
    { iata: "TLV", name: "Ben Gurion", city: "Tel Aviv", country: "Israel" },
    { iata: "AMM", name: "Queen Alia", city: "Amman", country: "Jordan" },
    { iata: "MCT", name: "Muscat International", city: "Muscat", country: "Oman" },
    { iata: "KWI", name: "Kuwait International", city: "Kuwait City", country: "Kuwait" },
    { iata: "BAH", name: "Bahrain International", city: "Manama", country: "Bahrain" },
    { iata: "DMM", name: "King Fahd International", city: "Dammam", country: "Saudi Arabia" },
    { iata: "MED", name: "Prince Mohammad bin Abdulaziz", city: "Medina", country: "Saudi Arabia" },
    { iata: "BOM", name: "Mumbai", city: "Mumbai", country: "India" },
    { iata: "MAA", name: "Chennai", city: "Chennai", country: "India" },
    { iata: "CCU", name: "Netaji Subhash Chandra Bose", city: "Kolkata", country: "India" },
    { iata: "HYD", name: "Rajiv Gandhi International", city: "Hyderabad", country: "India" },
    { iata: "DAC", name: "Shahjalal International", city: "Dhaka", country: "Bangladesh" },
    { iata: "KTM", name: "Tribhuvan International", city: "Kathmandu", country: "Nepal" },
    { iata: "CMB", name: "Bandaranaike International", city: "Colombo", country: "Sri Lanka" },
    { iata: "HAN", name: "Noi Bai International", city: "Hanoi", country: "Vietnam" },
    { iata: "DAD", name: "Da Nang International", city: "Da Nang", country: "Vietnam" },
    { iata: "REP", name: "Siem Reap–Angkor", city: "Siem Reap", country: "Cambodia" },
    { iata: "PNH", name: "Phnom Penh International", city: "Phnom Penh", country: "Cambodia" },
    { iata: "DPS", name: "Ngurah Rai International", city: "Bali", country: "Indonesia" },
    { iata: "CGK", name: "Soekarno–Hatta International", city: "Jakarta", country: "Indonesia" },
    { iata: "SUB", name: "Juanda International", city: "Surabaya", country: "Indonesia" },
    { iata: "BKI", name: "Kota Kinabalu International", city: "Kota Kinabalu", country: "Malaysia" },
    { iata: "PEN", name: "Penang International", city: "Penang", country: "Malaysia" },
    { iata: "CEB", name: "Mactan–Cebu International", city: "Cebu", country: "Philippines" },
    { iata: "HKT", name: "Phuket International", city: "Phuket", country: "Thailand" },
    { iata: "CNX", name: "Chiang Mai International", city: "Chiang Mai", country: "Thailand" },
    { iata: "FUK", name: "Fukuoka", city: "Fukuoka", country: "Japan" },
    { iata: "CTS", name: "New Chitose", city: "Sapporo", country: "Japan" },
    { iata: "NGO", name: "Chubu Centrair", city: "Nagoya", country: "Japan" },
    { iata: "GMP", name: "Gimpo International", city: "Seoul", country: "South Korea" },
    { iata: "PUS", name: "Gimhae International", city: "Busan", country: "South Korea" },
    { iata: "CJU", name: "Jeju International", city: "Jeju", country: "South Korea" },
    { iata: "CTU", name: "Chengdu Shuangliu", city: "Chengdu", country: "China" },
    { iata: "TFU", name: "Chengdu Tianfu", city: "Chengdu", country: "China" },
    { iata: "CKG", name: "Chongqing Jiangbei", city: "Chongqing", country: "China" },
    { iata: "KMG", name: "Kunming Changshui", city: "Kunming", country: "China" },
    { iata: "XIY", name: "Xi'an Xianyang", city: "Xi'an", country: "China" },
    { iata: "HGH", name: "Hangzhou Xiaoshan", city: "Hangzhou", country: "China" },
    { iata: "SWA", name: "Jieyang Chaoshan", city: "Shantou", country: "China" },
    { iata: "MFM", name: "Macau International", city: "Macau", country: "China" },
    { iata: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
    { iata: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia" },
    { iata: "CHC", name: "Christchurch International", city: "Christchurch", country: "New Zealand" },
    { iata: "NAN", name: "Nadi International", city: "Nadi", country: "Fiji" },
    { iata: "SAN", name: "San Diego International", city: "San Diego", country: "United States" },
    { iata: "TPA", name: "Tampa International", city: "Tampa", country: "United States" },
    { iata: "SLC", name: "Salt Lake City International", city: "Salt Lake City", country: "United States" },
    { iata: "DCA", name: "Ronald Reagan Washington National", city: "Washington D.C.", country: "United States" },
    { iata: "IAD", name: "Washington Dulles International", city: "Washington D.C.", country: "United States" },
    { iata: "BWI", name: "Baltimore/Washington International", city: "Baltimore", country: "United States" },
    { iata: "PDX", name: "Portland International", city: "Portland", country: "United States" },
    { iata: "STL", name: "St. Louis Lambert", city: "St. Louis", country: "United States" },
    { iata: "BNA", name: "Nashville International", city: "Nashville", country: "United States" },
    { iata: "AUS", name: "Austin-Bergstrom", city: "Austin", country: "United States" },
    { iata: "MSY", name: "Louis Armstrong New Orleans", city: "New Orleans", country: "United States" },
    { iata: "SJC", name: "San Jose International", city: "San Jose", country: "United States" },
    { iata: "OAK", name: "Oakland International", city: "Oakland", country: "United States" },
    { iata: "SMF", name: "Sacramento International", city: "Sacramento", country: "United States" },
    { iata: "SNA", name: "John Wayne Airport", city: "Santa Ana", country: "United States" },
    { iata: "RSW", name: "Southwest Florida International", city: "Fort Myers", country: "United States" },
    { iata: "PBI", name: "Palm Beach International", city: "West Palm Beach", country: "United States" },
    { iata: "CLE", name: "Cleveland Hopkins", city: "Cleveland", country: "United States" },
    { iata: "PIT", name: "Pittsburgh International", city: "Pittsburgh", country: "United States" },
    { iata: "CVG", name: "Cincinnati/Northern Kentucky", city: "Cincinnati", country: "United States" },
    { iata: "IND", name: "Indianapolis International", city: "Indianapolis", country: "United States" },
    { iata: "RDU", name: "Raleigh-Durham", city: "Raleigh", country: "United States" },
    { iata: "MKE", name: "Milwaukee Mitchell International", city: "Milwaukee", country: "United States" },
    { iata: "SAT", name: "San Antonio International", city: "San Antonio", country: "United States" },
    { iata: "HNL", name: "Daniel K. Inouye International", city: "Honolulu", country: "United States" },
    { iata: "ANC", name: "Ted Stevens Anchorage", city: "Anchorage", country: "United States" },
    { iata: "YOW", name: "Ottawa Macdonald-Cartier", city: "Ottawa", country: "Canada" },
    { iata: "YEG", name: "Edmonton International", city: "Edmonton", country: "Canada" },
    { iata: "YHZ", name: "Halifax Stanfield", city: "Halifax", country: "Canada" },
    { iata: "YWG", name: "Winnipeg Richardson", city: "Winnipeg", country: "Canada" },
    { iata: "TIJ", name: "Tijuana International", city: "Tijuana", country: "Mexico" },
    { iata: "SJD", name: "Los Cabos International", city: "San José del Cabo", country: "Mexico" },
    { iata: "PVR", name: "Licenciado Gustavo Díaz Ordaz", city: "Puerto Vallarta", country: "Mexico" },
    { iata: "MID", name: "Mérida International", city: "Mérida", country: "Mexico" },
    { iata: "BJX", name: "Bajío International", city: "León", country: "Mexico" },
    { iata: "SCQ", name: "Santiago de Compostela", city: "Santiago", country: "Spain" },
    { iata: "SVQ", name: "Sevilla", city: "Seville", country: "Spain" },
    { iata: "BIO", name: "Bilbao", city: "Bilbao", country: "Spain" },
    { iata: "TFN", name: "Tenerife Norte-Ciudad de La Laguna", city: "Tenerife", country: "Spain" },
    { iata: "TFS", name: "Tenerife Sur", city: "Tenerife", country: "Spain" },
    { iata: "LPA", name: "Gran Canaria", city: "Las Palmas", country: "Spain" },
    { iata: "ACE", name: "Lanzarote", city: "Lanzarote", country: "Spain" },
    { iata: "FUE", name: "Fuerteventura", city: "Fuerteventura", country: "Spain" },
    { iata: "IBZ", name: "Ibiza", city: "Ibiza", country: "Spain" },
    { iata: "MAH", name: "Menorca", city: "Mahón", country: "Spain" },
    { iata: "VGO", name: "Vigo", city: "Vigo", country: "Spain" },
    { iata: "LCG", name: "A Coruña", city: "A Coruña", country: "Spain" },
    { iata: "OVD", name: "Asturias", city: "Oviedo", country: "Spain" },
    { iata: "SDR", name: "Seve Ballesteros-Santander", city: "Santander", country: "Spain" },
    { iata: "GRX", name: "Federico García Lorca Granada-Jaén", city: "Granada", country: "Spain" },
    { iata: "MJV", name: "Región de Murcia", city: "Murcia", country: "Spain" },
    { iata: "XRY", name: "Jerez", city: "Jerez de la Frontera", country: "Spain" },
    { iata: "ZAZ", name: "Zaragoza", city: "Zaragoza", country: "Spain" },
    { iata: "REU", name: "Reus", city: "Reus", country: "Spain" },
    { iata: "GRO", name: "Girona-Costa Brava", city: "Girona", country: "Spain" },
    { iata: "VLL", name: "Valladolid", city: "Valladolid", country: "Spain" },
    { iata: "SPC", name: "La Palma", city: "Santa Cruz de la Palma", country: "Spain" },
    { iata: "VRA", name: "Juan Gualberto Gómez", city: "Varadero", country: "Cuba" },
    { iata: "HAV", name: "José Martí International", city: "Havana", country: "Cuba" },
    { iata: "KIN", name: "Norman Manley International", city: "Kingston", country: "Jamaica" },
    { iata: "MBJ", name: "Sangster International", city: "Montego Bay", country: "Jamaica" },
    { iata: "NAS", name: "Lynden Pindling International", city: "Nassau", country: "Bahamas" },
    { iata: "BGI", name: "Grantley Adams International", city: "Bridgetown", country: "Barbados" },
    { iata: "POS", name: "Piarco International", city: "Port of Spain", country: "Trinidad and Tobago" },
    { iata: "SJU", name: "Luis Muñoz Marín International", city: "San Juan", country: "Puerto Rico" },
    { iata: "CUR", name: "Curaçao International", city: "Willemstad", country: "Curaçao" },
    { iata: "AUA", name: "Queen Beatrix International", city: "Oranjestad", country: "Aruba" },
    { iata: "PTP", name: "Pointe-à-Pitre International", city: "Pointe-à-Pitre", country: "Guadeloupe" },
    { iata: "FDF", name: "Martinique Aimé Césaire", city: "Fort-de-France", country: "Martinique" },
    { iata: "LOS", name: "Murtala Muhammed International", city: "Lagos", country: "Nigeria" },
    { iata: "ABV", name: "Nnamdi Azikiwe International", city: "Abuja", country: "Nigeria" },
    { iata: "ACC", name: "Kotoka International", city: "Accra", country: "Ghana" },
    { iata: "DKR", name: "Blaise Diagne International", city: "Dakar", country: "Senegal" },
    { iata: "DSS", name: "Blaise Diagne International", city: "Dakar", country: "Senegal" },
    { iata: "TUN", name: "Tunis–Carthage", city: "Tunis", country: "Tunisia" },
    { iata: "RAK", name: "Marrakesh Menara", city: "Marrakesh", country: "Morocco" },
    { iata: "AGA", name: "Agadir–Al Massira", city: "Agadir", country: "Morocco" },
    { iata: "ALG", name: "Houari Boumediene", city: "Algiers", country: "Algeria" },
    { iata: "KRT", name: "Khartoum International", city: "Khartoum", country: "Sudan" },
    { iata: "DAR", name: "Julius Nyerere International", city: "Dar es Salaam", country: "Tanzania" },
    { iata: "ZNZ", name: "Abeid Amani Karume International", city: "Zanzibar", country: "Tanzania" },
    { iata: "MRU", name: "Sir Seewoosagur Ramgoolam", city: "Plaine Magnien", country: "Mauritius" },
    { iata: "TNR", name: "Ivato International", city: "Antananarivo", country: "Madagascar" },
    { iata: "LAD", name: "Quatro de Fevereiro", city: "Luanda", country: "Angola" },
    { iata: "EBB", name: "Entebbe International", city: "Entebbe", country: "Uganda" },
    { iata: "KGL", name: "Kigali International", city: "Kigali", country: "Rwanda" },
    { iata: "DLA", name: "Douala International", city: "Douala", country: "Cameroon" },
    { iata: "NSI", name: "Yaoundé Nsimalen", city: "Yaoundé", country: "Cameroon" },
    { iata: "LBV", name: "Leon M'ba International", city: "Libreville", country: "Gabon" },
    { iata: "BKO", name: "Modibo Keita International", city: "Bamako", country: "Mali" },
    { iata: "OUA", name: "Thomas Sankara", city: "Ouagadougou", country: "Burkina Faso" },
    { iata: "CKY", name: "Conakry International", city: "Conakry", country: "Guinea" },
    { iata: "FNA", name: "Lungi International", city: "Freetown", country: "Sierra Leone" },
    { iata: "ROB", name: "Roberts International", city: "Monrovia", country: "Liberia" },
    { iata: "LFW", name: "Gnassingbé Eyadéma", city: "Lomé", country: "Togo" },
    { iata: "COO", name: "Cotonou Cadjehoun", city: "Cotonou", country: "Benin" },
    { iata: "PHC", name: "Port Harcourt International", city: "Port Harcourt", country: "Nigeria" },
    { iata: "KAN", name: "Mallam Aminu Kano", city: "Kano", country: "Nigeria" },
    { iata: "WDH", name: "Hosea Kutako International", city: "Windhoek", country: "Namibia" },
    { iata: "GBE", name: "Sir Seretse Khama", city: "Gaborone", country: "Botswana" },
    { iata: "HRE", name: "Robert Gabriel Mugabe", city: "Harare", country: "Zimbabwe" },
    { iata: "LUN", name: "Kenneth Kaunda", city: "Lusaka", country: "Zambia" },
    { iata: "VFA", name: "Victoria Falls", city: "Victoria Falls", country: "Zimbabwe" },
    { iata: "RUN", name: "Roland Garros", city: "Saint-Denis", country: "Réunion" },
    { iata: "SEZ", name: "Seychelles International", city: "Victoria", country: "Seychelles" },
    { iata: "MLE", name: "Velana International", city: "Malé", country: "Maldives" },
    { iata: "ULN", name: "Chinggis Khaan International", city: "Ulaanbaatar", country: "Mongolia" },
    { iata: "ALA", name: "Almaty International", city: "Almaty", country: "Kazakhstan" },
    { iata: "NQZ", name: "Nursultan Nazarbayev International", city: "Astana", country: "Kazakhstan" },
    { iata: "TAS", name: "Tashkent International", city: "Tashkent", country: "Uzbekistan" },
    { iata: "ASB", name: "Ashgabat International", city: "Ashgabat", country: "Turkmenistan" },
    { iata: "EVN", name: "Zvartnots International", city: "Yerevan", country: "Armenia" },
    { iata: "GYD", name: "Heydar Aliyev International", city: "Baku", country: "Azerbaijan" },
    { iata: "TBS", name: "Tbilisi International", city: "Tbilisi", country: "Georgia" },
    { iata: "KBP", name: "Boryspil International", city: "Kyiv", country: "Ukraine" },
    { iata: "IEV", name: "Kyiv International (Zhuliany)", city: "Kyiv", country: "Ukraine" },
    { iata: "ODS", name: "Odesa International", city: "Odesa", country: "Ukraine" },
    { iata: "LWO", name: "Lviv International", city: "Lviv", country: "Ukraine" },
    { iata: "MSQ", name: "Minsk National", city: "Minsk", country: "Belarus" },
    { iata: "SVO", name: "Sheremetyevo International", city: "Moscow", country: "Russia" },
    { iata: "DME", name: "Domodedovo International", city: "Moscow", country: "Russia" },
    { iata: "VKO", name: "Vnukovo International", city: "Moscow", country: "Russia" },
    { iata: "LED", name: "Pulkovo Airport", city: "Saint Petersburg", country: "Russia" },
    { iata: "OVB", name: "Tolmachevo Airport", city: "Novosibirsk", country: "Russia" },
    { iata: "SVX", name: "Koltsovo Airport", city: "Yekaterinburg", country: "Russia" },
    { iata: "KGD", name: "Khrabrovo Airport", city: "Kaliningrad", country: "Russia" },
    { iata: "VVO", name: "Vladivostok International", city: "Vladivostok", country: "Russia" },
    { iata: "ULV", name: "Ulyanovsk Baratayevka", city: "Ulyanovsk", country: "Russia" },
    { iata: "KRR", name: "Krasnodar International", city: "Krasnodar", country: "Russia" },
    { iata: "AER", name: "Sochi International", city: "Sochi", country: "Russia" },
    { iata: "UFA", name: "Ufa International", city: "Ufa", country: "Russia" },
    { iata: "KZN", name: "Kazan International", city: "Kazan", country: "Russia" },
    { iata: "TSV", name: "Townsville", city: "Townsville", country: "Australia" },
    { iata: "CNS", name: "Cairns", city: "Cairns", country: "Australia" },
    { iata: "HBA", name: "Hobart", city: "Hobart", country: "Australia" },
    { iata: "DRW", name: "Darwin", city: "Darwin", country: "Australia" },
    { iata: "OOL", name: "Gold Coast", city: "Gold Coast", country: "Australia" },
    { iata: "WLG", name: "Wellington", city: "Wellington", country: "New Zealand" },
    { iata: "ZQN", name: "Queenstown", city: "Queenstown", country: "New Zealand" },
    { iata: "DUD", name: "Dunedin", city: "Dunedin", country: "New Zealand" },
    { iata: "NOU", name: "La Tontouta", city: "Nouméa", country: "New Caledonia" },
    { iata: "PPT", name: "Fa'a'ā International", city: "Papeete", country: "French Polynesia" },
    { iata: "APW", name: "Faleolo International", city: "Apia", country: "Samoa" },
    { iata: "TBU", name: "Fua'amotu International", city: "Nuku'alofa", country: "Tonga" },
    { iata: "VLI", name: "Bauerfield International", city: "Port Vila", country: "Vanuatu" },
    { iata: "HIR", name: "Honiara International", city: "Honiara", country: "Solomon Islands" },
    { iata: "POM", name: "Jacksons International", city: "Port Moresby", country: "Papua New Guinea" },
    { iata: "MAW", name: "Malampaya", city: "El Nido", country: "Philippines" },
    { iata: "MPH", name: "Caticlan (Boracay)", city: "Malay", country: "Philippines" },
    { iata: "USU", name: "Francisco B. Reyes", city: "Coron", country: "Philippines" },
    { iata: "DVO", name: "Francisco Bangoy International", city: "Davao", country: "Philippines" },
    { iata: "ILO", name: "Iloilo International", city: "Iloilo", country: "Philippines" },
    { iata: "Bacolod", name: "Bacolod–Silay", city: "Silay", country: "Philippines" },
    { iata: "BWN", name: "Brunei International", city: "Bandar Seri Begawan", country: "Brunei" },
    { iata: "LPQ", name: "Luang Prabang", city: "Luang Prabang", country: "Laos" },
    { iata: "VTE", name: "Wattay International", city: "Vientiane", country: "Laos" },
    { iata: "RGN", name: "Yangon International", city: "Yangon", country: "Myanmar" },
    { iata: "MDL", name: "Mandalay International", city: "Mandalay", country: "Myanmar" },
    { iata: "COK", name: "Cochin International", city: "Kochi", country: "India" },
    { iata: "TRV", name: "Trivandrum International", city: "Thiruvananthapuram", country: "India" },
    { iata: "AMD", name: "Sardar Vallabhbhai Patel", city: "Ahmedabad", country: "India" },
    { iata: "GOI", name: "Dabolim", city: "Goa", country: "India" },
    { iata: "GOX", name: "Manohar International", city: "Goa", country: "India" },
    { iata: "PNQ", name: "Pune Airport", city: "Pune", country: "India" },
    { iata: "LKO", name: "Chaudhary Charan Singh", city: "Lucknow", country: "India" },
    { iata: "JAI", name: "Jaipur International", city: "Jaipur", country: "India" },
    { iata: "SXR", name: "Sheikh ul-Alam", city: "Srinagar", country: "India" },
    { iata: "ATQ", name: "Sri Guru Ram Dass Jee", city: "Amritsar", country: "India" },
    { iata: "KHI", name: "Jinnah International", city: "Karachi", country: "Pakistan" },
    { iata: "LHE", name: "Allama Iqbal International", city: "Lahore", country: "Pakistan" },
    { iata: "ISB", name: "Islamabad International", city: "Islamabad", country: "Pakistan" },
    { iata: "SKD", name: "Skardu", city: "Skardu", country: "Pakistan" },
    { iata: "MCT", name: "Muscat", city: "Muscat", country: "Oman" },
    { iata: "SLL", name: "Salalah", city: "Salalah", country: "Oman" },
    { iata: "KTM", name: "Kathmandu", city: "Kathmandu", country: "Nepal" },
    { iata: "PBH", name: "Paro", city: "Paro", country: "Bhutan" },
    { iata: "KBP", name: "Boryspil", city: "Kyiv", country: "Ukraine" },
    { iata: "MSQ", name: "Minsk", city: "Minsk", country: "Belarus" },
    { iata: "EVN", name: "Yerevan", city: "Yerevan", country: "Armenia" },
    { iata: "GYD", name: "Baku", city: "Baku", country: "Azerbaijan" },
    { iata: "TBS", name: "Tbilisi", city: "Tbilisi", country: "Georgia" },
    { iata: "KIV", name: "Chișinău International", city: "Chișinău", country: "Moldova" },
    { iata: "TIA", name: "Tirana International", city: "Tirana", country: "Albania" },
    { iata: "SKP", name: "Skopje International", city: "Skopje", country: "North Macedonia" },
    { iata: "PRN", name: "Pristina International", city: "Pristina", country: "Kosovo" },
    { iata: "TGD", name: "Podgorica", city: "Podgorica", country: "Montenegro" },
    { iata: "TIV", name: "Tivat", city: "Tivat", country: "Montenegro" },
    { iata: "SJJ", name: "Sarajevo International", city: "Sarajevo", country: "Bosnia and Herzegovina" },
    { iata: "ZAG", name: "Zagreb", city: "Zagreb", country: "Croatia" },
    { iata: "SPU", name: "Split", city: "Split", country: "Croatia" },
    { iata: "DBV", name: "Dubrovnik", city: "Dubrovnik", country: "Croatia" },
    { iata: "LJU", name: "Ljubljana Jože Pučnik", city: "Ljubljana", country: "Slovenia" },
    { iata: "BTS", name: "M. R. Štefánik", city: "Bratislava", country: "Slovakia" },
    { iata: "LUX", name: "Luxembourg Findel", city: "Luxembourg City", country: "Luxembourg" },
    { iata: "MLA", name: "Malta International", city: "Luqa", country: "Malta" },
    { iata: "LCA", name: "Larnaca International", city: "Larnaca", country: "Cyprus" },
    { iata: "PFO", name: "Paphos International", city: "Paphos", country: "Cyprus" },
    { iata: "RKV", name: "Reykjavík", city: "Reykjavík", country: "Iceland" },
    { iata: "KEF", name: "Keflavík International", city: "Reykjavík", country: "Iceland" },
    { iata: "FAE", name: "Vágar", city: "Sørvágur", country: "Faroe Islands" },
    { iata: "GOH", name: "Nuuk", city: "Nuuk", country: "Greenland" },
    { iata: "SFJ", name: "Kangerlussuaq", city: "Kangerlussuaq", country: "Greenland" },
    { iata: "ANC", name: "Anchorage", city: "Anchorage", country: "United States" },
    { iata: "FAI", name: "Fairbanks International", city: "Fairbanks", country: "United States" },
    { iata: "JNU", name: "Juneau International", city: "Juneau", country: "United States" },
    { iata: "KTN", name: "Ketchikan International", city: "Ketchikan", country: "United States" },
    { iata: "SIT", name: "Sitka Rocky Gutierrez", city: "Sitka", country: "United States" },
    { iata: "PSG", name: "Petersburg James A. Johnson", city: "Petersburg", country: "United States" },
    { iata: "WRG", name: "Wrangell", city: "Wrangell", country: "United States" },
    { iata: "YAK", name: "Yakutat", city: "Yakutat", country: "United States" },
    { iata: "CDV", name: "Merle K. (Mudhole) Smith", city: "Cordova", country: "United States" },
    { iata: "ADQ", name: "Kodiak", city: "Kodiak", country: "United States" },
    { iata: "DLG", name: "Dillingham", city: "Dillingham", country: "United States" },
    { iata: "BET", name: "Bethel", city: "Bethel", country: "United States" },
    { iata: "OME", name: "Nome", city: "Nome", country: "United States" },
    { iata: "OTZ", name: "Ralph Wien Memorial", city: "Kotzebue", country: "United States" },
    { iata: "SCC", name: "Deadhorse", city: "Prudhoe Bay", country: "United States" },
    { iata: "BRW", name: "Wiley Post–Will Rogers Memorial", city: "Utqiagvik", country: "United States" },
    { iata: "STT", name: "Cyril E. King", city: "St. Thomas", country: "US Virgin Islands" },
    { iata: "STX", name: "Henry E. Rohlsen", city: "St. Croix", country: "US Virgin Islands" },
    { iata: "EIS", name: "Terrance B. Lettsome", city: "Beef Island", country: "British Virgin Islands" },
    { iata: "SXM", name: "Princess Juliana International", city: "St. Maarten", country: "Sint Maarten" },
    { iata: "SBH", name: "Gustaf III", city: "St. Jean", country: "Saint Barthélemy" },
    { iata: "ANU", name: "V. C. Bird International", city: "St. John's", country: "Antigua and Barbuda" },
    { iata: "SKB", name: "Robert L. Bradshaw", city: "Basseterre", country: "Saint Kitts and Nevis" },
    { iata: "SLU", name: "George F. L. Charles", city: "Castries", country: "Saint Lucia" },
    { iata: "UVF", name: "Hewanorra International", city: "Vieux Fort", country: "Saint Lucia" },
    { iata: "SVD", name: "Argyle International", city: "Kingstown", country: "Saint Vincent and the Grenadines" },
    { iata: "GND", name: "Maurice Bishop International", city: "St. George's", country: "Grenada" },
    { iata: "TAB", name: "A. N. R. Robinson International", city: "Scarborough", country: "Trinidad and Tobago" },
    { iata: "BON", name: "Flamingo International", city: "Kralendijk", country: "Bonaire" },
    { iata: "GEO", name: "Cheddi Jagan International", city: "Georgetown", country: "Guyana" },
    { iata: "PBM", name: "Johan Adolf Pengel International", city: "Paramaribo", country: "Suriname" },
    { iata: "CAY", name: "Cayenne – Félix Eboué", city: "Cayenne", country: "French Guiana" },
    { iata: "BZE", name: "Philip S. W. Goldson International", city: "Belize City", country: "Belize" },
    { iata: "RTB", name: "Juan Manuel Gálvez International", city: "Roatán", country: "Honduras" },
    { iata: "SAP", name: "Ramón Villeda Morales International", city: "San Pedro Sula", country: "Honduras" },
    { iata: "TGU", name: "Toncontín International", city: "Tegucigalpa", country: "Honduras" },
    { iata: "XPL", name: "Palmerola International", city: "Comayagua", country: "Honduras" },
    { iata: "MGA", name: "Augusto C. Sandino International", city: "Managua", country: "Nicaragua" },
    { iata: "LIR", name: "Daniel Oduber Quirós International", city: "Liberia", country: "Costa Rica" },
    { iata: "ADZ", name: "Gustavo Rojas Pinilla International", city: "San Andrés", country: "Colombia" },
    { iata: "CTG", name: "Rafael Núñez International", city: "Cartagena", country: "Colombia" },
    { iata: "BAQ", name: "Ernesto Cortissoz International", city: "Barranquilla", country: "Colombia" },
    { iata: "SMR", name: "Simón Bolívar International", city: "Santa Marta", country: "Colombia" },
    { iata: "PEI", name: "Matecaña International", city: "Pereira", country: "Colombia" },
    { iata: "CLO", name: "Alfonso Bonilla Aragón", city: "Cali", country: "Colombia" },
    { iata: "BGA", name: "Palonegro International", city: "Bucaramanga", country: "Colombia" },
    { iata: "CUC", name: "Camilo Daza International", city: "Cúcuta", country: "Colombia" },
    { iata: "GYE", name: "José Joaquín de Olmedo", city: "Guayaquil", country: "Ecuador" },
    { iata: "GPS", name: "Seymour Airport", city: "Baltra", country: "Ecuador" },
    { iata: "SCY", name: "San Cristóbal", city: "San Cristóbal", country: "Ecuador" },
    { iata: "CUZ", name: "Alejandro Velasco Astete International", city: "Cusco", country: "Peru" },
    { iata: "IQT", name: "Coronel FAP Francisco Secada Vignetta International", city: "Iquitos", country: "Peru" },
    { iata: "AQP", name: "Rodríguez Ballón International", city: "Arequipa", country: "Peru" },
    { iata: "LPB", name: "El Alto International", city: "La Paz", country: "Bolivia" },
    { iata: "CBB", name: "Jorge Wilstermann International", city: "Cochabamba", country: "Bolivia" },
    { iata: "ANF", name: "Andrés Sabella", city: "Antofagasta", country: "Chile" },
    { iata: "IQQ", name: "Diego Aracena", city: "Iquique", country: "Chile" },
    { iata: "PMC", name: "El Tepual", city: "Puerto Montt", country: "Chile" },
    { iata: "PUQ", name: "Presidente Carlos Ibáñez del Campo", city: "Punta Arenas", country: "Chile" },
    { iata: "IPC", name: "Mataveri International", city: "Easter Island", country: "Chile" },
    { iata: "MDZ", name: "Governor Francisco Gabrielli International", city: "Mendoza", country: "Argentina" },
    { iata: "COR", name: "Ingeniero Aeronáutico Ambrosio L.V. Taravella International", city: "Córdoba", country: "Argentina" },
    { iata: "BRC", name: "San Carlos de Bariloche", city: "Bariloche", country: "Argentina" },
    { iata: "USH", name: "Malvinas Argentinas International", city: "Ushuaia", country: "Argentina" },
    { iata: "IGR", name: "Mayor Carlos Eduardo Krause International", city: "Puerto Iguazú", country: "Argentina" },
    { iata: "POA", name: "Salgado Filho International", city: "Porto Alegre", country: "Brazil" },
    { iata: "CWB", name: "Afonso Pena International", city: "Curitiba", country: "Brazil" },
    { iata: "FLN", name: "Hercílio Luz International", city: "Florianópolis", country: "Brazil" },
    { iata: "CNF", name: "Tancredo Neves International", city: "Belo Horizonte", country: "Brazil" },
    { iata: "SSA", name: "Deputado Luís Eduardo Magalhães International", city: "Salvador", country: "Brazil" },
    { iata: "REC", name: "Guararapes – Gilberto Freyre International", city: "Recife", country: "Brazil" },
    { iata: "FOR", name: "Pinto Martins International", city: "Fortaleza", country: "Brazil" },
    { iata: "MAO", name: "Eduardo Gomes International", city: "Manaus", country: "Brazil" },
    { iata: "BEL", name: "Val-de-Cans International", city: "Belém", country: "Brazil" },
    { iata: "NAT", name: "Greater Natal International", city: "Natal", country: "Brazil" },
    { iata: "MCZ", name: "Zumbi dos Palmares International", city: "Maceió", country: "Brazil" },
    { iata: "GYN", name: "Santa Genoveva", city: "Goiânia", country: "Brazil" },
    { iata: "CGB", name: "Marechal Rondon International", city: "Cuiabá", country: "Brazil" },
    { iata: "CCS", name: "Simón Bolívar International", city: "Caracas", country: "Venezuela" },
    { iata: "MAR", name: "La Chinita International", city: "Maracaibo", country: "Venezuela" },
    { iata: "PMV", name: "Santiago Mariño International", city: "Porlamar", country: "Venezuela" },
    { iata: "BLA", name: "General José Antonio Anzoátegui International", city: "Barcelona", country: "Venezuela" },
    { iata: "MUN", name: "José Tadeo Monagas International", city: "Maturín", country: "Venezuela" },
    { iata: "VIG", name: "Juan Pablo Pérez Alfonzo", city: "El Vigía", country: "Venezuela" },
    { iata: "LSP", name: "Josefa Camejo International", city: "Punto Fijo", country: "Venezuela" },
    { iata: "SVZ", name: "Juan Vicente Gómez International", city: "San Antonio del Táchira", country: "Venezuela" },
    { iata: "BRM", name: "Jacinto Lara International", city: "Barquisimeto", country: "Venezuela" },
    { iata: "KSU", name: "Kristiansund", city: "Kristiansund", country: "Norway" },
    { iata: "AES", name: "Ålesund", city: "Ålesund", country: "Norway" },
    { iata: "MOL", name: "Molde", city: "Molde", country: "Norway" },
    { iata: "TRD", name: "Trondheim", city: "Trondheim", country: "Norway" },
    { iata: "BOO", name: "Bodø", city: "Bodø", country: "Norway" },
    { iata: "TOS", name: "Tromsø", city: "Tromsø", country: "Norway" },
    { iata: "ALF", name: "Alta", city: "Alta", country: "Norway" },
    { iata: "KKN", name: "Kirkenes", city: "Kirkenes", country: "Norway" },
    { iata: "LYR", name: "Svalbard", city: "Longyearbyen", country: "Norway" },
    { iata: "MMX", name: "Malmö", city: "Malmö", country: "Sweden" },
    { iata: "BMA", name: "Stockholm Bromma", city: "Stockholm", country: "Sweden" },
    { iata: "NYO", name: "Stockholm Skavsta", city: "Stockholm", country: "Sweden" },
    { iata: "VBY", name: "Visby", city: "Visby", country: "Sweden" },
    { iata: "UME", name: "Umeå", city: "Umeå", country: "Sweden" },
    { iata: "LLA", name: "Luleå", city: "Luleå", country: "Sweden" },
    { iata: "TKU", name: "Turku", city: "Turku", country: "Finland" },
    { iata: "TMP", name: "Tampere–Pirkkala", city: "Tampere", country: "Finland" },
    { iata: "RVN", name: "Rovaniemi", city: "Rovaniemi", country: "Finland" },
    { iata: "OUL", name: "Oulu", city: "Oulu", country: "Finland" },
    { iata: "AAR", name: "Aarhus", city: "Aarhus", country: "Denmark" },
    { iata: "EBJ", name: "Esbjerg", city: "Esbjerg", country: "Denmark" },
    { iata: "ORK", name: "Cork", city: "Cork", country: "Ireland" },
    { iata: "NOC", name: "Ireland West", city: "Knock", country: "Ireland" },
    { iata: "BFS", name: "Belfast International", city: "Belfast", country: "United Kingdom" },
    { iata: "BHD", name: "George Best Belfast City", city: "Belfast", country: "United Kingdom" },
    { iata: "ABZ", name: "Aberdeen", city: "Aberdeen", country: "United Kingdom" },
    { iata: "NCL", name: "Newcastle", city: "Newcastle", country: "United Kingdom" },
    { iata: "LPL", name: "Liverpool John Lennon", city: "Liverpool", country: "United Kingdom" },
    { iata: "EMA", name: "East Midlands", city: "Derby", country: "United Kingdom" },
    { iata: "LCY", name: "London City", city: "London", country: "United Kingdom" },
    { iata: "LTN", name: "London Luton", city: "London", country: "United Kingdom" },
    { iata: "SOU", name: "Southampton", city: "Southampton", country: "United Kingdom" },
    { iata: "EXT", name: "Exeter", city: "Exeter", country: "United Kingdom" },
    { iata: "CWL", name: "Cardiff", city: "Cardiff", country: "United Kingdom" },
    { iata: "JER", name: "Jersey", city: "Saint Helier", country: "Jersey" },
    { iata: "GCI", name: "Guernsey", city: "Saint Peter Port", country: "Guernsey" },
    { iata: "IOM", name: "Isle of Man", city: "Castletown", country: "Isle of Man" },
    { iata: "LIL", name: "Lille", city: "Lille", country: "France" },
    { iata: "SXB", name: "Strasbourg", city: "Strasbourg", country: "France" },
    { iata: "MLH", name: "EuroAirport Basel Mulhouse Freiburg", city: "Mulhouse", country: "France" },
    { iata: "NTE", name: "Nantes Atlantique", city: "Nantes", country: "France" },
    { iata: "BOD", name: "Bordeaux–Mérignac", city: "Bordeaux", country: "France" },
    { iata: "MPL", name: "Montpellier–Méditerranée", city: "Montpellier", country: "France" },
    { iata: "BIA", name: "Bastia – Poretta", city: "Bastia", country: "France" },
    { iata: "AJA", name: "Ajaccio Napoleon Bonaparte", city: "Ajaccio", country: "France" },
    { iata: "PGF", name: "Perpignan–Rivesaltes", city: "Perpignan", country: "France" },
    { iata: "BIQ", name: "Biarritz Pays Basque", city: "Biarritz", country: "France" },
    { iata: "PUY", name: "Pula", city: "Pula", country: "Croatia" },
    { iata: "RJK", name: "Rijeka", city: "Rijeka", country: "Croatia" },
    { iata: "ZAD", name: "Zadar", city: "Zadar", country: "Croatia" },
    { iata: "BWK", name: "Bol", city: "Brač", country: "Croatia" },
    { iata: "OSI", name: "Osijek", city: "Osijek", country: "Croatia" },
    { iata: "TSR", name: "Timișoara Traian Vuia", city: "Timișoara", country: "Romania" },
    { iata: "CLJ", name: "Cluj International", city: "Cluj-Napoca", country: "Romania" },
    { iata: "IAS", name: "Iași International", city: "Iași", country: "Romania" },
    { iata: "SBZ", name: "Sibiu International", city: "Sibiu", country: "Romania" },
    { iata: "SOF", name: "Sofia", city: "Sofia", country: "Bulgaria" },
    { iata: "VAR", name: "Varna", city: "Varna", country: "Bulgaria" },
    { iata: "BOJ", name: "Burgas", city: "Burgas", country: "Bulgaria" },
    { iata: "SKG", name: "Thessaloniki", city: "Thessaloniki", country: "Greece" },
    { iata: "HER", name: "Heraklion", city: "Heraklion", country: "Greece" },
    { iata: "RHO", name: "Rhodes International", city: "Rhodes", country: "Greece" },
    { iata: "CFU", name: "Corfu International", city: "Corfu", country: "Greece" },
    { iata: "CHQ", name: "Chania International", city: "Chania", country: "Greece" },
    { iata: "KGS", name: "Kos International", city: "Kos", country: "Greece" },
    { iata: "JTR", name: "Santorini", city: "Santorini", country: "Greece" },
    { iata: "JMK", name: "Mykonos", city: "Mykonos", country: "Greece" },
    { iata: "ZTH", name: "Zakynthos International", city: "Zakynthos", country: "Greece" },
    { iata: "EFL", name: "Kefalonia International", city: "Kefalonia", country: "Greece" },
    { iata: "KLX", name: "Kalamata International", city: "Kalamata", country: "Greece" },
    { iata: "GPA", name: "Araxos", city: "Patras", country: "Greece" },
    { iata: "VOL", name: "Nea Anchialos", city: "Volos", country: "Greece" },
    { iata: "KVA", name: "Kavala International", city: "Kavala", country: "Greece" },
    { iata: "SMI", name: "Samos International", city: "Samos", country: "Greece" },
    { iata: "MJT", name: "Mytilene International", city: "Lesbos", country: "Greece" },
    { iata: "JKH", name: "Chios Island National", city: "Chios", country: "Greece" },
    { iata: "AOK", name: "Karpathos Island National", city: "Karpathos", country: "Greece" },
    { iata: "JNX", name: "Naxos Island National", city: "Naxos", country: "Greece" },
    { iata: "PAS", name: "Paros National", city: "Paros", country: "Greece" },
    { iata: "MIL", name: "Milan Metropolitan", city: "Milan", country: "Italy" },
    { iata: "LIN", name: "Milan Linate", city: "Milan", country: "Italy" },
    { iata: "BGY", name: "Orio al Serio", city: "Bergamo", country: "Italy" },
    { iata: "TRN", name: "Turin", city: "Turin", country: "Italy" },
    { iata: "GOA", name: "Genoa", city: "Genoa", country: "Italy" },
    { iata: "VRN", name: "Verona Villafranca", city: "Verona", country: "Italy" },
    { iata: "VBS", name: "Brescia Montichiari", city: "Brescia", country: "Italy" },
    { iata: "TSF", name: "Treviso", city: "Treviso", country: "Italy" },
    { iata: "BLQ", name: "Bologna Guglielmo Marconi", city: "Bologna", country: "Italy" },
    { iata: "PSA", name: "Pisa International", city: "Pisa", country: "Italy" },
    { iata: "FLR", name: "Florence", city: "Florence", country: "Italy" },
    { iata: "AOI", name: "Ancona Falconara", city: "Ancona", country: "Italy" },
    { iata: "CIA", name: "Rome Ciampino", city: "Rome", country: "Italy" },
    { iata: "PSR", name: "Abruzzo", city: "Pescara", country: "Italy" },
    { iata: "BRI", name: "Bari Karol Wojtyła", city: "Bari", country: "Italy" },
    { iata: "BDS", name: "Brindisi – Salento", city: "Brindisi", country: "Italy" },
    { iata: "SUF", name: "Lamezia Terme International", city: "Lamezia Terme", country: "Italy" },
    { iata: "REG", name: "Reggio Calabria", city: "Reggio Calabria", country: "Italy" },
    { iata: "PMO", name: "Palermo", city: "Palermo", country: "Italy" },
    { iata: "TPS", name: "Trapani Birgi", city: "Trapani", country: "Italy" },
    { iata: "CIY", name: "Comiso", city: "Comiso", country: "Italy" },
    { iata: "CAG", name: "Cagliari Elmas", city: "Cagliari", country: "Italy" },
    { iata: "OLB", name: "Olbia Costa Smeralda", city: "Olbia", country: "Italy" },
    { iata: "AHO", name: "Alghero–Fertilia", city: "Alghero", country: "Italy" },
    { iata: "BGO", name: "Bergen", city: "Bergen", country: "Norway" },
    { iata: "AES", name: "Ålesund", city: "Ålesund", country: "Norway" },
    { iata: "SDA", name: "Baghdad International", city: "Baghdad", country: "Iraq" },
    { iata: "EBL", name: "Erbil International", city: "Erbil", country: "Iraq" },
    { iata: "ISL", name: "Atatürk", city: "Istanbul", country: "Turkey" },
    { iata: "TZX", name: "Trabzon", city: "Trabzon", country: "Turkey" },
    { iata: "ERZ", name: "Erzurum", city: "Erzurum", country: "Turkey" },
    { iata: "ASR", name: "Kayseri Erkilet", city: "Kayseri", country: "Turkey" },
    { iata: "GZT", name: "Gaziantep", city: "Gaziantep", country: "Turkey" },
    { iata: "ADA", name: "Adana Şakirpaşa", city: "Adana", country: "Turkey" },
    { iata: "BJV", name: "Milas–Bodrum", city: "Bodrum", country: "Turkey" },
    { iata: "DLM", name: "Dalaman", city: "Dalaman", country: "Turkey" },
    { iata: "GZP", name: "Gazipaşa–Alanya", city: "Alanya", country: "Turkey" },
    { iata: "KCO", name: "Kocaeli Cengiz Topel", city: "Izmit", country: "Turkey" },
    { iata: "HTY", name: "Hatay", city: "Antakya", country: "Turkey" },
    { iata: "VAS", name: "Sivas Nuri Demirag", city: "Sivas", country: "Turkey" },
    { iata: "MLX", name: "Malatya Erhaç", city: "Malatya", country: "Turkey" },
    { iata: "DIY", name: "Diyarbakır", city: "Diyarbakır", country: "Turkey" },
    { iata: "EZS", name: "Elazığ", city: "Elazığ", country: "Turkey" },
    { iata: "VAN", name: "Van Ferit Melen", city: "Van", country: "Turkey" },
    { iata: "KWW", name: "Kerman", city: "Kerman", country: "Iran" },
    { iata: "MHD", name: "Mashhad International", city: "Mashhad", country: "Iran" },
    { iata: "SYZ", name: "Shiraz International", city: "Shiraz", country: "Iran" },
    { iata: "TBZ", name: "Tabriz International", city: "Tabriz", country: "Iran" },
    { iata: "IKA", name: "Imam Khomeini International", city: "Tehran", country: "Iran" },
    { iata: "THR", name: "Mehrabad International", city: "Tehran", country: "Iran" },
    { iata: "IFN", name: "Isfahan International", city: "Isfahan", country: "Iran" },
    { iata: "BND", name: "Bandar Abbas International", city: "Bandar Abbas", country: "Iran" },
    { iata: "AWZ", name: "Ahvaz International", city: "Ahvaz", country: "Iran" },
    { iata: "AZD", name: "Yazd Sadooghi", city: "Yazd", country: "Iran" },
    { iata: "OMH", name: "Urmia", city: "Urmia", country: "Iran" },
    { iata: "KSH", name: "Kermanshah", city: "Kermanshah", country: "Iran" },
    { iata: "KIH", name: "Kish International", city: "Kish Island", country: "Iran" },
    { iata: "GSM", name: "Qeshm International", city: "Qeshm Island", country: "Iran" },
    { iata: "ZAH", name: "Zahedan", city: "Zahedan", country: "Iran" },
    { iata: "SRW", name: "Sarawak", city: "Sarawak", country: "Malaysia" },
    { iata: "BKI", name: "Kota Kinabalu", city: "Kota Kinabalu", country: "Malaysia" },
    { iata: "KCH", name: "Kuching", city: "Kuching", country: "Malaysia" },
    { iata: "MYY", name: "Miri", city: "Miri", country: "Malaysia" },
    { iata: "TGG", name: "Sultan Mahmud", city: "Kuala Terengganu", country: "Malaysia" },
    { iata: "KBR", name: "Sultan Ismail Petra", city: "Kota Bharu", country: "Malaysia" },
    { iata: "AOR", name: "Sultan Abdul Halim", city: "Alor Setar", country: "Malaysia" },
    { iata: "KUA", name: "Sultan Haji Ahmad Shah", city: "Kuantan", country: "Malaysia" },
    { iata: "MKZ", name: "Malacca International", city: "Malacca", country: "Malaysia" },
    { iata: "JHB", name: "Senai International", city: "Johor Bahru", country: "Malaysia" },
    { iata: "BTU", name: "Bintulu", city: "Bintulu", country: "Malaysia" },
    { iata: "LBU", name: "Labuan", city: "Labuan", country: "Malaysia" },
    { iata: "LKW", name: "Langkawi International", city: "Langkawi", country: "Malaysia" },
    { iata: "SZB", name: "Sultan Abdul Aziz Shah", city: "Subang", country: "Malaysia" },
    { iata: "SDK", name: "Sandakan", city: "Sandakan", country: "Malaysia" },
    { iata: "TWU", name: "Tawau", city: "Tawau", country: "Malaysia" },
    { iata: "KRA", name: "Kerang", city: "Kerang", country: "Australia" },
    { iata: "PBO", name: "Paraburdoo", city: "Paraburdoo", country: "Australia" },
    { iata: "KTA", name: "Karratha", city: "Karratha", country: "Australia" },
    { iata: "PHE", name: "Port Hedland International", city: "Port Hedland", country: "Australia" },
    { iata: "BME", name: "Broome International", city: "Broome", country: "Australia" },
    { iata: "KNX", name: "Kununurra", city: "Kununurra", country: "Australia" },
    { iata: "ASP", name: "Alice Springs", city: "Alice Springs", country: "Australia" },
    { iata: "AYQ", name: "Ayers Rock", city: "Uluru", country: "Australia" },
    { iata: "ISA", name: "Mount Isa", city: "Mount Isa", country: "Australia" },
    { iata: "LRE", name: "Longreach", city: "Longreach", country: "Australia" },
    { iata: "ROK", name: "Rockhampton", city: "Rockhampton", country: "Australia" },
    { iata: "GLT", name: "Gladstone", city: "Gladstone", country: "Australia" },
    { iata: "MCY", name: "Sunshine Coast", city: "Sunshine Coast", country: "Australia" },
    { iata: "BNK", name: "Ballina Byron Gateway", city: "Ballina", country: "Australia" },
    { iata: "CFS", name: "Coffs Harbour", city: "Coffs Harbour", country: "Australia" },
    { iata: "PQQ", name: "Port Macquarie", city: "Port Macquarie", country: "Australia" },
    { iata: "NTL", name: "Newcastle", city: "Newcastle", country: "Australia" },
    { iata: "WGA", name: "Wagga Wagga", city: "Wagga Wagga", country: "Australia" },
    { iata: "ABX", name: "Albury", city: "Albury", country: "Australia" },
    { iata: "MQL", name: "Mildura", city: "Mildura", country: "Australia" },
    { iata: "LST", name: "Launceston", city: "Launceston", country: "Australia" },
    { iata: "DPO", name: "Devonport", city: "Devonport", country: "Australia" },
    { iata: "BWT", name: "Burnie", city: "Burnie", country: "Australia" },
    { iata: "KGI", name: "Kalgoorlie", city: "Kalgoorlie", country: "Australia" },
    { iata: "GET", name: "Geraldton", city: "Geraldton", country: "Australia" },
    { iata: "LEA", name: "Learmonth", city: "Exmouth", country: "Australia" },
    { iata: "XCH", name: "Christmas Island", city: "Christmas Island", country: "Australia" },
    { iata: "CCK", name: "Cocos (Keeling) Islands", city: "Cocos Islands", country: "Australia" },
    { iata: "NLK", name: "Norfolk Island", city: "Norfolk Island", country: "Australia" },
    { iata: "ZAD", name: "Zadar", city: "Zadar", country: "Croatia" },
    { iata: "RJK", name: "Rijeka", city: "Rijeka", country: "Croatia" },
    { iata: "PUY", name: "Pula", city: "Pula", country: "Croatia" },
    { iata: "BWK", name: "Brač", city: "Brač", country: "Croatia" },
    { iata: "OSI", name: "Osijek", city: "Osijek", country: "Croatia" },
    { iata: "SJJ", name: "Sarajevo", city: "Sarajevo", country: "Bosnia and Herzegovina" },
    { iata: "BNX", name: "Banja Luka International", city: "Banja Luka", country: "Bosnia and Herzegovina" },
    { iata: "OMO", name: "Mostar", city: "Mostar", country: "Bosnia and Herzegovina" },
    { iata: "TZL", name: "Tuzla International", city: "Tuzla", country: "Bosnia and Herzegovina" },
    { iata: "TGD", name: "Podgorica", city: "Podgorica", country: "Montenegro" },
    { iata: "TIV", name: "Tivat", city: "Tivat", country: "Montenegro" },
    { iata: "PRN", name: "Pristina", city: "Pristina", country: "Kosovo" },
    { iata: "TIA", name: "Tirana", city: "Tirana", country: "Albania" },
    { iata: "SKP", name: "Skopje", city: "Skopje", country: "North Macedonia" },
    { iata: "OHD", name: "Ohrid St. Paul the Apostle", city: "Ohrid", country: "North Macedonia" }
    ];

    for (const airport of airports){
        await prisma.airport.upsert({
            where: { iata: airport.iata },
            update: {},
            create: airport
        });
    }

    console.log("Aeropuertos cargados ", airports.length);
}
